config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :articles, only: [:new, :create]
  end
  resources :articles, only: [:index, :show, :edit, :update, :destroy]

  post '/articles/:article_id/comments',
    to: 'comments#create_comment',
    as: 'article_comments'

end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
  has_many :tags
  has_many :comments, as: :commentable

  attr_accessor :keywords

  @@alchemy_url ||= ENV["ALCHEMY_URL"]

  def get_keywords
    res = Typhoeus.get(
      @@alchemy_url,
      params: {
        apikey: ENV["ALCHEMY_APIKEY"],
        text: content,
        maxRetrieve: 10,
        outputMode: "json"
      }
    )
    words = JSON.parse(res.body)["keywords"].map { |w| w['text'] }
    @keywords = words.join(" | ")
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # callbacks
  before_action :require_login
  before_action :find_user, only: [:new, :create, :auth_user?]
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :auth_user?, only: [:new, :edit]

  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /users/:user_id/articles/new
  def new
    @article = Article.new
    @title = 'New article'
  end

  # GET /articles/:id
  def show
    # Alchemy API
    # if @article.tags.empty? && @article.content.split.size > 100
    #   @article.get_keywords
    #   ...
    # end
    @comments = @article.comments
  end

  # GET /articles/:id/edit
  def edit
    @user = @article.user
    @title = 'Edit article'
  end

  # POST /users/:user_id/articles
  def create
    @article = Article.new article_params
    if @article.save
      @user.articles << @article
      redirect_to article_path(@article),
        flash: { success: "Article published!" }
    else
      flash.now[:danger] = "Please fix these errors: #{@article.errors.messages}"
      render :new
    end
  end

  # PATCH /articles/:id
  def update
    if @article.update article_params
      redirect_to article_path(@article),
        flash: { success: "Changes saved!" }
    else
      flash.now[:danger] = "Please fix these errors: #{@article.errors.messages}"
      render :edit
    end
  end

  # DELETE /articles/:id
  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def find_user
    @user = User.find params[:user_id]
  end

  def find_article
    @article = Article.find params[:id]
  end

  def auth_user?
    # do not execute the find_article callback before this method,
    # because having @article.user.id in the code will crash if @article is nil
    # (which it may be if we're coming here from articles#new)
    # instead, call find_user and use those results to determine how to set user_id
    if @user
      user_id = @user.id
    else
      user_id = Article.find(params[:id]).user.id
    end
    unless current_user.id == user_id
      # layout: false prevents the application layout page from loading
      # returning false/true stops/allows the action
      render file: 'public/401.html', status: 401, layout: false
      false
    else
      true
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= render partial: 'shared/article_form',
    locals: { article: @article, user: @user,
                title: @title, new_article: false } %>

app/views/articles/index.html.erb
<div class="container"><br>

  <%= link_to 'Post new article', new_user_article_path(current_user) %>
  <br>

  <% if @articles.empty? %>

    <h3>No articles to show</h3>

  <% else %>

    <h3>Articles</h3>
    <hr>
    <ul class='list-unstyled'>
      <% @articles.each do |article| %>
        <li> <%= link_to article.title, article_path(article) %> </li>
      <% end %>
    </ul>

  <% end %>

</div>

app/views/articles/new.html.erb
<%= render partial: 'shared/article_form',
    locals: { article: @article, user: @user,
                title: @title, new_article: true } %>

app/views/articles/show.html.erb
<div class='container'><br>

  <div class='col-md-6'>

    <%= link_to 'All articles', articles_path %>
    <br>

    <h3><%= @article.title %></h3>
    <h4>by
      <a href="<%= user_path(@article.user) %>">
        <%= @article.user.first_name %> <%= @article.user.last_name %>
      </a>
    </h4>

    <hr>
      <p><%= @article.content %></p>
    <hr>

    <% if current_user.id == @article.user.id %>
      <div class='row'>
        <div class='col-md-2'>
          <%= button_to 'Edit article', edit_article_path(@article),
              { method: :get, class: 'btn btn-primary' } %>
        </div>
        <div class='col-md-2'>
          <%= button_to 'Delete article', article_path(@article),
              { method: :delete, data: { confirm: 'Are you sure?' },
                 class: 'btn btn-danger' } %>
        </div>
      </div>
    <% end %>

  </div>
  <br>
  <div class='col-md-6'>
    <!-- inserting a row gives me a smaller set of 12 columns
    so I can get the spacing I want -->
    <div class='row'>
      <div class='col-md-10 col-md-offset-1'>

        <h3>Comments</h3>

        <%= form_for [@article, Comment.new] do |f| %>

            <%= f.text_area :content, :rows => 3, :cols => 58 %>
            <br>
            <div class='row'>
              <div class='col-md-4 col-md-offset-8'>
                <%= f.submit "Add comment", class: 'btn btn-primary' %>
              </div>
            </div>

        <% end %><br>

        <% @comments.each do |comment| %>
          <p>
            <%= comment.content %> - <%= time_ago_in_words comment.created_at %> ago by <strong><%= User.find(comment.user_id).email %></strong>
          </p>
        <% end %>

      </div>
    </div>
  </div>

</div>