config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :articles, only: [:new, :create]
  end
  resources :articles, only: [:index, :show, :edit, :update, :destroy]

  post '/articles/:article_id/comments',
    to: 'comments#create_comment',
    as: 'article_comments'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  # validations
  validates :email, presence: true, uniqueness: true, confirmation: true
  # email_confirmation is a virtual field added when confirmation: true
  # is set on the email attribute.  if nil the confirmation won't be done,
  # so validate its presence
  validates :email_confirmation, presence: true, if: :new_record?

  # associations
  has_many :articles

  # paperclip
  has_attached_file :avatar,
            styles: { medium: "300x300>", thumb: "100x100>" },
       default_url: ':style/missing-avatar.jpg'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  # returns @user or false
  def self.confirm user_params
    user = User.find_by(email: user_params[:email])
    user.try(:authenticate, user_params[:password])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login, only: [:show, :edit, :destroy]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :auth_user?, only: :edit

  # GET /users/new
  def new
    @user = User.new
    @title = "Sign up"
  end

  # GET /users/:id
  def show
  end

  # GET /users/:id/edit
  def edit
    @title = 'Edit profile'
  end

  # POST /users
  def create
    @user = User.new user_params
    if @user.save
      login @user
      redirect_to @user, flash: { success: "Welcome, #{@user.first_name}!" }
    else
      flash.now[:danger] = "Please fix these errors: #{@user.errors.messages}"
      render :new
    end
  end

  # PATCH /users/:id
  def update
    if @user.update user_params
      redirect_to user_path(@user),
        flash: { success: "Changes saved" }
    else
      flash.now[:danger] = "Please fix these errors: #{@user.errors.messages}"
      render :edit
    end
  end

  # DELETE /user/:id
  def destroy
    logout
    @user.destroy
    redirect_to root_path,
        flash: { info: "Fine.  We didn't like you anyway."}
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,
      :email_confirmation, :password, :password_confirmation, :avatar)
  end

  def find_user
    @user = User.find params[:id]
  end

  def auth_user?
    # layout: false prevents the application layout page from loading
    # returning false/true stops/allows the action
    unless current_user.id == params[:id].to_i
      render file: 'public/401.html', status: 401, layout: false
      false
    else
      true
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render partial: 'shared/user_form',
    locals: { user: @user, title: @title } %>

app/views/users/new.html.erb
<%= render partial: 'shared/user_form',
    locals: { user: @user, title: @title } %>

app/views/users/show.html.erb
<div class='container'>

    <div class='col-md-3'><br>

      <%= image_tag @user.avatar.url(:thumb) %>
      <h3> <%= @user.first_name %> <%= @user.last_name %> </h3>
      <h4> <%= @user.email %> </h4>

      <% if current_user.id == @user.id %>

        <%= link_to 'Edit profile', edit_user_path(@user) %>
        <br><br><br>

        <%= button_to 'Delete my account', user_path(@user),
            { method: :delete, data: { confirm: "Are you sure?" },
              class: 'alert alert-danger' } %>

      <% end %>

    </div>

    <div class='col-md-9'><br>

      <% if current_user.id == @user.id %>
        <%= link_to 'Post new article', new_user_article_path(@user) %>&nbsp|&nbsp
      <% end %>
      <%= link_to 'All articles', articles_path %>
      <br><br>

      <h4> Articles by <%= @user.first_name %> <%= @user.last_name %> </h4>
      <hr>
      <% @user.articles.each do |article| %>
        <ul class='list-unstyled'>
          <li> <%= link_to article.title, article_path(article) %> </li>
        </ul>
      <% end %>
      <hr>

    </div>

</div>