config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :articles, only: [:new, :create]
  end
  resources :articles, only: [:index, :show, :edit, :update, :destroy]

  post '/articles/:article_id/comments',
    to: 'comments#create_comment',
    as: 'article_comments'

end

app/views/shared/_article_form.html.erb
<div class='container'>

  <div class='col-md-6'>
    <!-- nest a row so I can put the title and cancel link on the same line -->
    <div class='row'>

      <div class='col-md-8'>
        <% if params[:action] == 'new' || params[:action] == 'create' %>
          <h2>New article</h2>
        <% else %>
          <h2>Edit article</h2>
        <% end %>
      </div>
      <!-- padding is necessary to vertically align the link with the headline -->
      <div class='col-md-4 text-right' style='padding-top: 34px'>
        <%= link_to 'Cancel', :back %>
      </div>

    </div>

    <%= form_for article,
        url: (new_article ? user_articles_path : article_path) do |f| %>

      <div clas='form-group'>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', autofocus: "true"  %>
      </div>
      <br>

      <div class='form-group'>
        <%= f.label :content %>
        <%= f.text_area :content, class: 'form-control', size: "60x12" %>
      </div>

      <div class='row'>
        <div class='col-md-12'>
          <%= f.submit class: 'btn btn-primary pull-right' %>
        </div>
      </div>

    <% end %>

  </div>

</div>

app/views/shared/_user_form.html.erb
<div class='col-md-4 col-md-offset-4'>
  <div class='well'>

    <div class='row'>  <!-- form heading -->

      <div class='col-md-6'>
        <h3><%= title %></h3>
      </div>

      <div class='col-md-6 text-right'>
        <% if params[:action] == 'new' %>
          <div style='padding-top: 8px'>
            Already registered?<br>
            <%= link_to 'Sign in', login_path %>
          </div>
        <% else %>
          <div style='padding-top: 27px'>
            <%= link_to 'Cancel', user_path(user) %>
          </div>
        <% end %>
      </div>

    </div><br>  <!-- form heading -->

    <%= form_for user, html: { multipart: true } do |f| %>

      <div class='form-group'>
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>

      <div class='form-group'>
        <%= f.label :email %>
       <%= f.email_field :email, class: 'form-control' %>
      </div>

      <% if params[:action] == 'new' %>

        <div class='form-group'>
          <%= f.label :email_confirmation %>
          <%= f.email_field :email_confirmation, class: 'form-control' %>
        </div>

        <div class='form-group'>
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class='form-group'>
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

      <% end %>

      <% if params[:action] == 'edit' %>

        <div class='form-group'>
          <%= f.label :avatar %>
          <%= f.file_field :avatar %>
        </div>

      <% end %>

      <%= f.submit class: 'btn btn-primary pull-right' %>

    <% end %>
    <br><br>

  </div>
</div>