config/routes.rb
Rails.application.routes.draw do

  root 'site#index'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :articles, only: [:new, :create]
  end
  resources :articles, only: [:index, :show, :edit, :update, :destroy]

  post '/articles/:article_id/comments',
    to: 'comments#create_comment',
    as: 'article_comments'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-static-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse_button">
          <span class="sr-only">Toggle navigation</span>
        </button>
        <a class="navbar-brand" href="javascript:;">Blog App</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <% if current_user %>
        <div class="collapse navbar-collapse" id="collapse_button">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to 'My Profile', user_path(current_user) %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to 'Logout', logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      <% end %>

    </div><!-- /.container-fluid -->
  </nav>

  <!-- Flash messaging -->
  <% flash.each do |type, msg| %>
    <!-- type: success, info, warning, danger -->
    <% if msg.is_a?(String) %>
      <div class="text-center alert alert-<%= type %>" role="alert">
        <button type="button" class="close" data-dismiss="alert"
                aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{type}" %>
      </div>
    <% end %>
  <% end %>

  <%= yield %>

</body>
</html>